#!/bin/sh

! [ -f /usr/bin/iwinfo ] && {
  echo iwinfo not found
  exit 1
}

! [ -f /tmp/dhcp.leases ]; then
  echo dhcp.leases not found
  exit 1
}

DHCP=`cat /tmp/dhcp.leases`
echo -e "IP address\tSignal\tTX/RX\t\tHW address\t\tDevice\tHostname"

for i in `iwinfo | cut -d\  -f1 | xargs`; do
  DUMP=`iwinfo $i assoclist`
  for j in `echo "$DUMP" | grep SNR | cut -d\  -f1`; do
    STATION=`echo "$DUMP" | grep -A 3 $j`
    IP=`echo "$DHCP" | grep -i $j | cut -d\  -f3`
    HOSTNAME=`echo "$DHCP" | grep -i $j | cut -d\  -f4`
    SIGNAL=`echo "$STATION" | grep SNR | xargs | cut -d\  -f2`
    TX=`echo "$STATION" | grep TX | xargs | cut -d\  -f2`
    RX=`echo "$STATION" | grep RX | xargs | cut -d\  -f2`
    echo -e "$IP\t$SIGNAL\t$TX/$RX\t$j\t$i\t$HOSTNAME"
  done
done
