#!/bin/sh

! [ -f /usr/bin/iwinfo ] && ! [ -f /usr/sbin/iwconfig ] && {
  echo iwinfo/iwconfig not found
  exit 1
}

if ! [ -f /tmp/dhcp.leases ]; then
  DHCP=`ssh -i /etc/dropbear/dropbear_rsa_host_key 10.0.0.10 "cat /tmp/dhcp.leases"`
else
  DHCP=`cat /tmp/dhcp.leases`
fi
echo -e "IP address\tSignal\tTX/RX\t\tHW address\t\tDevice\tHostname"

for i in `iwconfig 2>&1 | grep IEEE | cut -d\  -f1`; do
  DUMP=`iwinfo $i assoclist`
  for j in `echo "$DUMP" | grep SNR | cut -d\  -f1`; do
    STATION=`echo "$DUMP" | grep -A 3 $j`
    IP=`echo "$DHCP" | grep -i $j | cut -d\  -f3`
    HOSTNAME=`echo "$DHCP" | grep -i $j | cut -d\  -f4`
    SIGNAL=`echo "$STATION" | grep SNR | xargs | cut -d\  -f2`
    TX=`echo "$STATION" | grep TX | xargs | cut -d\  -f2`
    RX=`echo "$STATION" | grep RX | xargs | cut -d\  -f2`
    echo -e "$IP\t$SIGNAL\t$TX/$RX\t$j\t$i\t$HOSTNAME"
  done
done
